# Generated by Django 4.0.4 on 2024-02-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine_app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='Email',
        ),
    ]
