# Generated by Django 4.0.4 on 2024-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine_app', '0003_rename_email_signup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
        migrations.AddField(
            model_name='signup',
            name='Username',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
