# Generated by Django 4.0.4 on 2024-02-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine_app', '0004_remove_signup_username_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
