# Generated by Django 4.0.4 on 2024-07-24 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine_app', '0005_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
