# Generated by Django 4.0.4 on 2024-07-24 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine_app', '0006_signup_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='Username',
        ),
        migrations.AddField(
            model_name='signup',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='m_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
